{
	"version": 1635678726,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/button_play-sheet0.png",
		"images/button_pause-sheet0.png",
		"images/button_stop-sheet0.png",
		"images/forwards-sheet0.png",
		"images/back-sheet0.png",
		"images/home-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/eye-sheet0.png",
		"images/next-sheet0.png",
		"media/airplane trips.ogg",
		"media/apartment living.ogg",
		"media/bus travel.ogg",
		"media/buying cars.ogg",
		"media/b-airplanetickets-1.ogg",
		"media/calendars and dates.ogg",
		"media/campus housing.ogg",
		"media/clothing and fashion.ogg",
		"media/conversation starters.ogg",
		"media/dinner ideas.ogg",
		"media/directions around town (1).ogg",
		"media/directions around town (2).ogg",
		"media/directions around town (3).ogg",
		"media/english language program.ogg",
		"media/esl programs.ogg",
		"media/family relationships.ogg",
		"media/finding hotels.ogg",
		"media/hobbies.ogg",
		"media/holiday party.ogg",
		"media/house cleaning.ogg",
		"media/introductions.ogg",
		"media/job search 1.ogg",
		"media/job search 2.ogg",
		"media/making friends.ogg",
		"media/making-friends--randalls-esl-cyber-listening-lab.ogg",
		"media/movies.ogg",
		"media/names meeting people.ogg",
		"media/new clothing.ogg",
		"media/part-time jobs.ogg",
		"media/phone numbers.ogg",
		"media/restaurants.ogg",
		"media/school schedule.ogg",
		"media/shopping and prices.ogg",
		"media/shopping centers.ogg",
		"media/sick day.ogg",
		"media/sports and recreation.ogg",
		"media/student living.ogg",
		"media/telephone.ogg",
		"media/telling time.ogg",
		"media/train trip planning.ogg",
		"media/travel and sightseeing.ogg",
		"media/university programs.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}